server:
  port: 8080
#  error:
#    path: /error
#  ssl:
#    key-store: httpsssl.p12
#    key-alias: tomcathttps
#    key-password: tomcathttps
#    enabled: false
  servlet:
    session:
      timeout: 30m
    context-path: /springbootvue
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
    basedir: /Users/tony/Desktop/uploadFile/
spring:
  http:
    encoding:
      force-response: true
  datasource:
    name: smile
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/smile
    username: root
    password: 88888888
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
#  data:
#    mongodb:
#      authentication-database: admin
#      database: test
#      host: localhost
#      port: 27017
#      username: sang
#      password: 123

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location: /Users/tony/Desktop/uploadFile/
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false
  thymeleaf:
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
    encoding: UTF-8
    cache: true
    check-template: true
    check-template-location: true
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/templates/
  redis:
    database: 0
    # 启动redis时指定配置文件，否则可能以保护模式启动，项目无法连接 redis-server ./redis.conf
    host: localhost
    port: 6379
    password: 123@456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  devtools:
    restart:
      enabled: true
      trigger-file: .trigger-file
      additional-paths: src/main/resources/templates
    livereload:
      enabled: true